set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-dispatch'
Plugin 'kien/ctrlp.vim'
Plugin 'altercation/vim-colors-solarized'
Plugin 'ntpeters/vim-better-whitespace'
Plugin 'nvie/vim-flake8'
Plugin 'scrooloose/syntastic'
Plugin 'fatih/vim-go'
Plugin 'rhysd/vim-go-impl'
Plugin 'godlygeek/tabular'

" Plugin 'davidhalter/jedi-vim'

Plugin 'Valloric/YouCompleteMe'

call vundle#end()            " required
filetype plugin indent on    " required

let g:flake8_ignore="E127,E121,E122"

set runtimepath^=~/.vim/bundle/ctrlp.vim
set rtp+=/usr/local/Cellar/go/1.3/libexec/misc/vim
let g:ctrlp_custom_ignore = {
  \ 'dir':  '\v[\/](build|\.(git|hg|svn))$',
  \ 'file': '\v\.(pyc|so)$',
  \ }

" Always show statusline
set laststatus=2

" Use 256 colours (Use this setting only if your terminal supports 256 colours)
set t_Co=256

python from powerline.vim import setup as powerline_setup
python powerline_setup()
python del powerline_setup

let g:solarized_termcolors=256
syntax enable
set background=dark
colorscheme solarized

set tabstop=4
set shiftwidth=4
set softtabstop=4
set smarttab
set expandtab
set pastetoggle=<f2>

map gn :bn<cr>
map gp :bp<cr>
map gd :bd<cr>

let g:syntastic_ruby_checkers = ['rubocop']
let g:syntastic_rake_checkers = ['rubocop']

" autocmd BufWritePost *.py call Flake8()

function! Browser ()
  let line = getline (".")
  let line = matchstr (line, "\%(http://\|www\.\)[^ ,;\t]*")
  exec "!open ".line
endfunction
map <Leader>w :call Browser ()<CR>

nnoremap <silent> <C-S> :<C-u>Update<CR>

let @p='Oimport pdb; pdb.set_trace()'
let @d=':%g/import pdb; pdb.set_trace/d<CR>'

autocmd Filetype python setlocal ts=4 sw=4 expandtab
autocmd Filetype ruby setlocal ts=2 sw=2 expandtab

let g:syntastic_go_checkers = ['golint', 'govet', 'errcheck']
let g:syntastic_mode_map = { 'mode': 'active', 'passive_filetypes': ['go'] }

let g:go_fmt_command = "goimports"
set backspace=indent,eol,start

let mapleader = ","
